# Prometheus 配置文件

global:
  scrape_interval: 15s        # 默认采集间隔
  evaluation_interval: 15s    # 告警规则评估间隔
  external_labels:
    cluster: 'traffic-monitor'
    environment: 'production'

# 告警管理器配置 (可选)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#             - alertmanager:9093

# 告警规则文件
rule_files:
  # - "alerts.yml"

# 采集目标配置
scrape_configs:
  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'
  
  # 检测服务监控
  - job_name: 'detection-service'
    static_configs:
      - targets: ['host.docker.internal:5000']
        labels:
          service: 'detection'
          component: 'pipeline'
  
  # LLM 调度器监控
  - job_name: 'llm-scheduler'
    static_configs:
      - targets: ['host.docker.internal:9091']
        labels:
          service: 'scheduler'
          component: 'llm-task'
  
  # Kafka Exporter 监控 (需要额外部署 kafka-exporter)
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
        labels:
          service: 'kafka'
          component: 'messaging'
  
  # Redis Exporter 监控 (需要额外部署 redis-exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'
          component: 'cache'
  
  # Node Exporter 监控 (系统资源)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node'
          component: 'system'
